version: '3.3'
services:
  db:
    image: 'mysql:latest'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_USER: db
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'db-data:/var/lib/mysql'
  mongo:
    image: 'mongo:latest'
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    expose:
      - '6379'
  seq:
    image: 'datalust/seq:latest'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 14G
        reservations:
          memory: 14G
    environment:
      ACCEPT_EULA: Y
    ports:
      - '5341:5341'
      - '8080:80'
    expose:
      - '8080'
    volumes:
      - 'seq-data:/data'
      
  prom:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini
    
volumes:
  db-data: null
  seq-data: null
  prometheus_data: null
